---
- name: Replace .bashrc for user root
  ansible.builtin.copy:
    src: root/bashrc
    dest: /root/.bashrc
    owner: root
    group: root
    mode: 0640

- name: Replace skel .bashrc
  ansible.builtin.copy:
    src: skel/bashrc
    dest: /etc/skel/.bashrc
    owner: root
    group: root
    mode: 0644
