---
- name: Disable Root Login
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: "PermitRootLogin no"
    state: present
  notify: restart sshd

- name: Set MaxAuthTries to 2
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^MaxAuthTries'
    line: "MaxAuthTries 2"
    state: present
  notify: restart sshd

- name: Set banner to /etc/issue.net
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#Banner none'
    line: "Banner /etc/issue.net"
    state: present
  notify: restart sshd
