---
- name: Install firewalld and ipset
  dnf:
    name:
      - firewalld
      - ipset

- name: Create ipset management
  shell: firewall-cmd --permanent --new-ipset=management --type=hash:net
  register: create_ipset_result
  failed_when: diff_cmd.rc != 0 or diff_cmd.rc != 26

- name: test
  prompt: Management IP?
  private: no
  when: create_ipset_result is defined

- name: Print a message
  ansible.builtin.debug:
    msg: 'Logging in as {{ test }}'
  when: test is defined

#- name: Create ipset management
#  shell: "firewall-cmd --permanent --ipset=management --add-entry={{ item }}"
#  with_items: "{{ management_source_ip }}"
#
- name: Create rich rule service SSH for ipset management
  ansible.posix.firewalld:
    rich_rule: rule source ipset="management" service name="ssh" accept
    zone: public
    permanent: yes
    state: enabled

- name: Close service cockpit for zone public
  firewalld: 
    service: cockpit
    permanent: true 
    zone: public
    state: disabled

- name: Close service ssh for zone public
  firewalld: 
    service: ssh
    permanent: true 
    zone: public
    state: disabled

- name: Restart and enable service firewalld
  service:
    name: firewalld
    enabled: yes
    state: restarted
