---
- name: Install firewalld and ipset
  dnf:
    name:
      - firewalld
      - ipset

- name: Create ipset management
  ansible.builtin.shell: firewall-cmd --permanent --new-ipset=management --type=hash:net
  register: create_ipset_result
  failed_when:
    - "create_ipset_result.rc != 0"
    - "create_ipset_result.rc != 26"

- name: Create rich rule service SSH for ipset management
  ansible.posix.firewalld:
    rich_rule: rule source ipset="management" service name="ssh" accept
    zone: public
    permanent: yes
    state: enabled
  notify: restart firewalld

- name: Close service cockpit for zone public
  firewalld: 
    service: cockpit
    permanent: true 
    zone: public
    state: disabled
  notify: restart firewalld

- name: Close service ssh for zone public
  firewalld: 
    service: ssh
    permanent: true 
    zone: public
    state: disabled
  notify: restart firewalld
